




import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  tboxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tbox',
    },
  ],

  tempBoxSidebar: [
    {
      type: 'autogenerated',
      dirName: 'tempbox',
    },
  ],
};

export default sidebars;








// --------------------Version 2
// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],
// };

// export default sidebars;















// --------------- Version 1
// import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

// const sidebars: SidebarsConfig = {
//   tboxSidebar: [
//     {
//       type: 'doc',
//       id: 'tbox/overview',
//       label: 'Overview',
//     },
//     {
//       type: 'category',
//       label: 'Communication',
//       collapsed: false,
//       items: [
//         'tbox/communication/overview',
//         'tbox/communication/serial-communication',
//         'tbox/communication/telegram-protocol',
//       ],
//     },
//     {
//       type: 'doc',
//       id: 'tbox/downloads',
//       label: 'Downloads',
//     },

//     {
//       type: 'html',
//       value: '<div class="sidebar-section-divider"></div>',
//       defaultStyle: false,
//     },

//     {
//       type: 'category',
//       label: 'TBOX',
//       collapsed: false,
//       items: [
//         'tbox/devices/tbox/technical-data',
//         'tbox/devices/tbox/hardware',
//         'tbox/devices/tbox/hardware-revisions',
//         'tbox/devices/tbox/changelog',
//       ],
//     },
//   ],
// };




// export default sidebars;